export enum BankEnum {
    SCB = 'SCB',
    KBANK = 'KBANK',
    BAY = 'BAY',
    KTB = 'KTB',
    TMB = 'TMB',
    BBL = 'BBL',
    KKP = 'KKP',
    CIMBT = 'CIMBT',
    TISCO = 'TISCO',
    TBANK = 'TBANK',
    UOBT = 'UOBT',
    TCD = 'TCD',
    LHFG = 'LHFG',
    ICBCT = 'ICBCT',
    SME = 'SME',
    BAAC = 'BAAC',
    EXIM = 'EXIM',
    GSB = 'GSB',
    GHB = 'GHB',
    ISBT = 'ISBT',
    TRUEWALLET = 'TRUEWALLET'
}